#!/usr/bin/env bash
echo "Testing Phpactor dependencies"
echo "============================="
echo ""

EXITCODE=0
php .travis/list-deps.php | while read -r dep; do
    echo ""
    echo "Testing: $dep"
    echo ""
    cd vendor/$dep

    if [ ! -e vendor ]; then
        ln -s ../../../vendor
    fi
    composer dumpautoload
    if [ $EXITCODE -eq 0 ] && ! vendor/bin/phpunit; then
         EXITCODE=1
    fi
    cd -
done

exit $EXITCODE
