#!/usr/bin/env bash
echo "Testing Phpactor dependencies"
echo "============================="
echo ""

EXITCODE=0
for dep in class-mover class-to-file code-builder code-transform source-code-filesystem worse-reflection completion docblock language-server class-to-file-extension completion-extension completion-rpc-extension completion-worse-extension composer-autoloader-extension file-path-resolver-extension logging-extension rpc-extension source-code-filesystem-extension worse-reflection-extension; do
    echo ""
    echo "Testing: "$dep
    echo ""
    cd vendor/phpactor/$dep

    if [ ! -e vendor ]; then
        ln -s ../../../vendor
    fi
    composer dumpautoload
    if [ $EXITCODE -eq 0 ] && ! vendor/bin/phpunit; then
         EXITCODE=1
    fi
    cd -
done

exit $EXITCODE
