#!/usr/bin/env bash
set -e
echo "Testing Installability of Phpactor Extensions"
echo "============================================="
echo ""

LIST=$(tr '\n' ' ' < ".travis/extensions-to-test")
echo "Extensions:"
echo ""
sed 's/^/  /' < .travis/extensions-to-test
echo ""
echo "Instatlling:"
echo ""
./bin/phpactor extension:install $LIST | sed 's/^/  /'
echo ""
echo "Done"
./bin/phpactor extension:list
