#!/usr/bin/env bash
echo "Testing Phpactor dependencies"
echo "============================="
echo ""

EXITCODE=0
while read -r dep; do
    echo ""
    echo "Testing: $dep"
    echo ""
    cd "vendor/$dep" || continue

    if [ ! -e vendor ]; then
        ln -s ../../../vendor .
    fi
    composer dumpautoload
    if [ $EXITCODE -eq 0 ] && ! vendor/bin/phpunit; then
         EXITCODE=1
    fi
    cd - || continue
done < <(php .travis/list-deps.php)

exit $EXITCODE
