#!/usr/bin/env bash
set -e
echo "Testing Installability of Phpactor Extensions"
echo "============================================="
echo ""

if [ ! -e '.phpactor.json' ]; then
    echo '{"extension_manager.minimum_stability":"dev"}' >> .phpactor.json
fi

LIST=$(tr '\n' ' ' < ".travis/extensions-to-test")
echo "Extensions:"
echo ""
sed 's/^/  /' < .travis/extensions-to-test
echo ""
echo "Instatlling:"
echo ""
./bin/phpactor extension:install $LIST
echo ""
echo "Done"
./bin/phpactor extension:list
